### ISSUE TITLE
testdataset ID SPEECHIO_ASR_ZH00006 can't pull?

### ISSUE THREAD

**Issue by thewintersun** [SpeechColab/Leaderboard#14]
root@multi-gpu-0:~/code/github/Leaderboard# ops/pull dataset SPEECHIO_ASR_ZH00006
2021-11-08 08:30:42,648 [INFO] Namespace(resource_id='SPEECHIO_ASR_ZH00006', resource_type='dataset')
Traceback (most recent call last):
  File "ops/pull", line 42, in <module>
    src = remote_dataset_zoo[dataset_id]['url']
KeyError: 'SPEECHIO_ASR_ZH00006'

and the dataset/zoom.yaml file not contain the config info of SPEECHIO_ASR_ZH00006??

**Comment by wbgxx333** [comment]
you should wait for some day. now only can access SPEECHIO_ASR_ZH00000---00003

**Comment by dophist** [comment]
You can refer to repo's README to find out released(unlocked) test sets.
