### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by learnxy** [SpeechColab/Leaderboard#25]
here:https://github.com/SpeechColab/Leaderboard/blob/master/models/tencent_api_zh/asr_api.py#L56
the `base64Wav = base64.b64encode(data)` should be `base64Wav = str(base64.b64encode(data),encoding="utf-8")`

**Comment by dophist** [comment]
The client uses python2 and the encoded data is str type already, and you are talking about python3-only syntax.
