### ISSUE TITLE
I sent oss.cnf email to leaderboard@speechio.ai but  not  get the reply,why?

### ISSUE THREAD

**Issue by lili161** [SpeechColab/Leaderboard#40]

**Comment by kli017** [comment]
@lili161 Did you get reply？

**Comment by lili161** [comment]
> @lili161 Did you get reply？

Do not use gmail or email server which beyound ''The Wall'',use QQ,163........

**Comment by kli017** [comment]
> > @lili161 Did you get reply？
> 
> Do not use gmail or email server which beyound ''The Wall'',use QQ,163........
Found it in the spam.. Thanks for the help
