### ISSUE TITLE
utils/oss无法在CentOS上运行

### ISSUE THREAD

**Issue by li563042811** [SpeechColab/Leaderboard#69]
oss是一个html文件，直接用ops/pull里面的命令行运行会报错，这个怎么解决呢

**Comment by dophist** [comment]
oss is a binary, not html.

We provide [downloading script here](https://github.com/SpeechColab/Leaderboard/blob/master/utils/install_aliyun_oss_client.sh), make sure you use it.

If it doesn't work, please provide your CPU architecture and more specific error messages.

**Comment by li563042811** [comment]
Thank for your reply.
I download the oss by the script. And when I run it, there is something wrong like below.
-----------------------------------------------------------------
$ ./oss
./oss: line 1: html: No such file or [directory](javascript:volid(0))
./oss: line 2: head: No such file or directory
./oss: line 3: meta: No such file or directory
./oss: line 4: title: No such file or directory
./oss: line 5: link: No such file or directory
./oss: line 6: $'\r': command not found
./oss: line 7: /head: No such file or directory
./oss: line 8: $'\r': command not found
./oss: line 9: script: No such file or directory
./oss: line 10: $'\r': command not found
./oss: line 11: //: Is a directory
./oss: line 12: var: command not found
./oss: line 12: $'\r': command not found
./oss: line 13: $'\r': command not found
./oss: line 14: syntax error near unexpected token `[str](javascript:volid(0))'
'/oss: line 14: `function defendXSSReplace(str){  

$ head oss
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>URL过滤</title>
<link href="../[css](javascript:volid(0))/terminal.css" rel="stylesheet" type="text/css" />

</head>

<script language="JavaScript" type="text/JavaScript">
--------------------------------------------------------------
It seems like not a binary.


> oss is a binary, not html.
> 
> We provide [downloading script here](https://github.com/SpeechColab/Leaderboard/blob/master/utils/install_aliyun_oss_client.sh), make sure you use it.
> 
> If it doesn't work, please provide your CPU architecture and more specific error messages.

**Comment by dophist** [comment]
oss is a ~10M binary.

 I'm not sure why it is not the case in your environment, try to check your oss downloading.
 I just checked the source link (in our script) is OK, I don't see anything that can be fixed from our side, unless you provide more info.

**Comment by li563042811** [comment]
wget -O $ossbin http://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64

**Comment by dophist** [comment]
cool, closing
